### ISSUE TITLE
PageController.page cannot be accessed before a PageView is built with it.

### ISSUE THREAD

**Issue by JoshRice1** [GeekyAnts/flutter-carousel#2]
Receive this error when I tap on my image in the carousel to rout to a new page

PageController.page cannot be accessed before a PageView is built with it.
'package:flutter/src/widgets/page_view.dart':
Failed assertion: line 179 pos 7: 'positions.isNotEmpty'
User-created ancestor of the error-causing widget was
    Carousel

**Comment by jaiswalshubham84** [comment]
@JoshRice1  It's hard to say with the error message that what actually is causing this issue.
If you can post your code implementation, it will be much easy for me to debug the issue and provide you a solution

**Comment by JoshRice1** [comment]
I resolved the issue bad on my part.
